services:
  db:
    image: postgis/postgis:latest
    volumes:
      - ./.postgres_data/db:/var/lib/postgresql/data
    ports:
      # from the host machine, the connection string would look like postgres://{DOCKER_IP}:8001
      # for example postgres://localhost:8001 if your container is running locally.
      - "8001:5432"
    environment:
      - POSTGRES_DB=ellipse_bikes
      - POSTGRES_USER=bike
      - POSTGRES_PASSWORD=bike
  web:
    build: .
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=ellipse_bikes
      - POSTGRES_USER=bike
      - POSTGRES_PASSWORD=bike
      - COMPOSE_DB_HOST=db
    depends_on:
      - db