# Generated by Django 5.0.4 on 2024-05-02 12:31
import json
from pathlib import Path
from django.db import migrations
from django.utils import timezone


# More into how to migrate data:
# https://docs.djangoproject.com/en/5.0/topics/migrations/#data-migrations
tz = timezone.get_current_timezone()
data_file_path = Path(__file__).parent.parent.resolve() / 'data' / 'contracts.json'
with open(data_file_path, 'r', encoding='utf8') as f:
    contracts = json.load(f)

cities = []
for contract in contracts:
    if contract['cities']:
        for city in contract['cities']:
            if city not in cities:
                cities.append(city)


def insert_city(apps, schema_editor):
    # We can't import the Station model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    City = apps.get_model("ellipse_bikes", "City")
    for city1 in cities:
        City.objects.create(
            name=city1,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ellipse_bikes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_city),
    ]
