# Generated by Django 5.0.4 on 2024-05-02 12:31
import json
from pathlib import Path
from django.db import migrations
from django.utils import timezone


# More into how to migrate data:
# https://docs.djangoproject.com/en/5.0/topics/migrations/#data-migrations
tz = timezone.get_current_timezone()
data_file_path = Path(__file__).parent.parent.resolve() / 'data' / 'contracts.json'
with open(data_file_path, 'r', encoding='utf8') as f:
    contracts = json.load(f)


def insert_contract(apps, schema_editor):
    # We can't import the Station model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Contract = apps.get_model("ellipse_bikes", "Contract")
    City = apps.get_model("ellipse_bikes", "City")
    for contract in contracts:
        cities = []
        if contract['cities']:
            for city in contract['cities']:
                cities.append(City.objects.get(name=city))
        saved_contract =  Contract.objects.create(
            name=contract['name'],
            commercial_name=contract['commercial_name'],
            country_code=contract['country_code'],
        )
        saved_contract.cities.add(*cities)
        saved_contract.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ellipse_bikes', '0002_insert_cities'),
    ]

    operations = [
        migrations.RunPython(insert_contract),
    ]
