# Generated by Django 5.0.4 on 2024-05-03 04:09
from datetime import timedelta
from django.db import migrations
from django.utils import timezone

from django_q.models import Schedule

def insert_schedule(apps, schema_editor):
    # For more details in the Schedule attributes:
    # https://django-q2.readthedocs.io/en/latest/schedules.html#django_q.Schedule.MINUTES
    Schedule.objects.create(
        func="ellipse_bikes.cron.func.update_stations",
        name="Update Stations Process",
        # Other options:
        # ONCE, MINUTES, HOURLY, DAILY, WEEKLY, BIWEEKLY, MONTHLY, BIMONTHLY, QUARTERLY, YEARLY, CRON
        schedule_type=Schedule.MINUTES,
        # The number of minutes the MINUTES schedule should use. Is ignored for other schedule types.
        minutes=15,
        # Number of times to repeat the schedule. -1=Always, 0=Never,n =n.
        # When set to -1, this will keep counting down.
        repeats=-1,
        next_run=timezone.now() + timedelta(minutes=3),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ellipse_bikes', '0004_insert_stations'),
    ]

    operations = [
        migrations.RunPython(insert_schedule),
    ]
